//socket actions
export const SOCKET_CONNECTED = 'SOCKET_CONNECTED'
export const SOCKET_DISCONNECTED = 'SOCKET_DISCONNECTED'

//hosting actions
export const HOST_GAME_REQUEST = 'HOST_GAME_REQUEST'
export const HOST_GAME_SUCCESS = 'HOST_GAME_SUCCESS'
export const HOST_GAME_FAILURE = 'HOST_GAME_FAILURE'
export const START_SETUP_REQUEST = 'START_SETUP_REQUEST'
export const START_SETUP_SUCCESS = 'START_SETUP_SUCCESS'
export const START_SETUP_FAILURE = 'START_SETUP_FAILURE'
export const SUBMIT_RULES_REQUEST = 'SUBMIT_RULES_REQUEST'
export const SUBMIT_RULES_SUCCESS = 'SUBMIT_RULES_SUCCESS'
export const SUBMIT_RULES_FAILURE = 'SUBMIT_RULES_FAILURE'

//joining actions
export const JOIN_GAME_REQUEST = 'JOIN_GAME_REQUEST'
export const JOIN_GAME_SUCCESS = 'JOIN_GAME_SUCCESS'
export const JOIN_GAME_FAILURE = 'JOIN_GAME_FAILURE'

//player actions
export const PLAYER_JOINED = 'PLAYER_JOINED'
export const PLAYER_DISCONNECTED = 'PLAYER_DISCONNECTED'
export const PLAYER_NAME_SET = 'PLAYER_NAME_SET'
export const SET_NAME_REQUEST = 'SET_NAME_REQUEST'
export const SET_NAME_SUCCESS = 'SET_NAME_SUCCESS'
export const SET_NAME_FAILURE = 'SET_NAME_FAILURE'
export const UPDATE_PLAYERS = 'UPDATE_PLAYERS'

//info actions
export const GIVE_PLAYER_INFO = 'GIVE_PLAYER_INFO'
export const SHOW_INFO = 'SHOW_INFO'
export const HIDE_INFO = 'HIDE_INFO'

//party leader actions
export const START_PARTY_SELECTION = 'START_PARTY_SELECTION'
export const SET_PARTY_LEADER = 'SET_PARTY_LEADER'
export const SELECT_PARTY_MEMBER_REQUEST = 'SELECT_PARTY_MEMBER_REQUEST'
export const SELECT_PARTY_MEMBER_SUCCESS = 'SELECT_PARTY_MEMBER_SUCCESS'
export const SELECT_PARTY_MEMBER_FAILURE = 'SELECT_PARTY_MEMBER_FAILURE'
export const CONFIRM_PARTY_REQUEST = 'CONFIRM_PARTY_REQUEST'
export const CONFIRM_PARTY_SUCCESS = 'CONFIRM_PARTY_SUCCESS'
export const CONFIRM_PARTY_FAILURE = 'CONFIRM_PARTY_FAILURE'

//vote actions
export const VOTE_ACCEPT_REJECT_REQUEST = 'VOTE_ACCEPT_REJECT_REQUEST'
export const VOTE_ACCEPT_REJECT_SUCCESS = 'VOTE_ACCEPT_REJECT_SUCCESS'
export const VOTE_ACCEPT_REJECT_FAILURE = 'VOTE_ACCEPT_REJECT_FAILURE'
export const VOTE_ACCEPT_REJECT_RESULTS = 'VOTE_ACCEPT_REJECT_RESULTS'
export const VOTE_PASS_FAIL_REQUEST = 'VOTE_PASS_FAIL_REQUEST'
export const VOTE_PASS_FAIL_SUCCESS = 'VOTE_PASS_FAIL_SUCCESS'
export const VOTE_PASS_FAIL_FAILURE = 'VOTE_PASS_FAIL_FAILURE'
export const VOTE_PASS_FAIL_RESULTS = 'VOTE_PASS_FAIL_RESULTS'

//quest actions
export const SET_QUEST_STATUS = 'SET_QUEST_STATUS'
export const UPDATE_QUESTS = 'UPDATE_QUESTS'